### ISSUE TITLE
[Suggestion] Add option to swap "Add Reminder" button for other methods of adding reminders

### ISSUE THREAD

**Issue by fowlis** [DevEvil99/Reminder-BetterDiscord-Plugin#1]
**Why?**
Personally, I like to keep my interface minimal. While I like the design and placement of this button, I do also find it a bit intrusive for my liking.

**Okay, so how else could it be done?**
I propose two options:
1. The "Add Reminder" button could be added to the plugin's settings panel. I personally like to have this sort of thing out of the way.
2. If possible, introduce client-side slash command functionality. I think this would make it super easy to create reminders if the regular button is hidden.

**Closing notes**
I appreciate this plugin. It's very convenient to me as I try to keep things "to myself" as much as possible. While it is reasonable to use bots for this case, it's convenient to be able to do it on my own client.

I understand if you are not taking suggestions on this plugin, but I would greatly appreciate if one of my proposed options, or even something similar, was introduced.

Thank you!

**Comment by DevEvil99** [comment]
Hello!

Thank you for your great suggestions. I truly appreciate and rely on feedback to improve my plugin for you, the users. However, since the plugin was just released, I don’t have plans to update it immediately, it’s still a bit too soon. That said, I will definitely consider your suggestions for future updates.

To address the two options you proposed:

1. In my opinion, adding the reminder panel to the settings menu would negatively affect the UX, as it would make it more complicated. I want it to remain easily accessible!


2. I don’t think it’s possible to create slash commands with plugin (or perhaps I’m not aware of how to do it), and I’m unsure if implementing that functionality would be "legal".

Thank you for using Reminder 🫂
